name: Continuous Integration

on:
  workflow_run:
    workflows: ["Terraform"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22"
      - name: Build backend
        run: go build -v ./...
        working-directory: backend
      - name: Test backend
        run: go test -v ./...
        working-directory: backend
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install frontend dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./frontend
      - name: Build frontend
        run: yarn build
        working-directory: ./frontend
      - name: Test frontend
        run: yarn test
        working-directory: ./frontend
       